# 网易云配置
cookie: 1eb9ce22024bb666e99b6743b2222f29ef64a9e88fda0fd5754714b900a5d70d993166e004087dd3b95085f6a85b059f5e9aba41e3f2646e3cebdbec0317df58c119e5;os=pc;appver=8.9.75 # 不用单引号或双引号
uid: 123456  # 网易云用户ID

# 日志级别
LEVEL: "INFO"

# 下载音乐的品质
#     """音质等级枚举"""
#     "standard"    # 标准
#     "exhigh"      # 极高
#     "lossless"    # 无损
#     "hires"       # Hi-Res
#     "sky"         # 沉浸环绕声
#     "jyeffect"    # 高清环绕声
#     "jymaster"    # 超清母带
QUALITY_LEVEL: "lossless"


# Navidrome配置
NAVIDROME:
  NAVIDROME_HOST: "http://192.168.0.6:4533"
  NAVIDROME_USER: "admin"
  NAVIDROME_PASS: "admin"
  # 是否开启 Navidrome 检查
  USE_NAVIDROME: true

# music-tag-web
mysql:
  # 是否检查music-tag-web使用的MySQL数据库
  USE_MYSQL: false
  # 服务器IP地址
  host: 192.168.0.6
  # 端口号（默认MySQL端口为3306）
  port: 3306
  # 数据库用户名
  user: root
  # 数据库密码
  password: password
  # 数据库名称
  database: music_tag
# Bark通知配置
BARK_API: "https://api.day.app/your_key/"

# 定时任务配置 (cron格式: 分 时 日 月 周)
# 每天20:00-23:30之间每30分钟执行一次
CRON_SCHEDULE: "0,30 20-23 * * *"